insert into public.catcare_product_catalog
  (item_type, brand, product_name, display_name, aliases, country_region)
values
  ('dry_food', '皇家', '绝育成猫粮', '皇家 绝育成猫粮', array['Royal Canin Sterilised'], 'FR'),
  ('dry_food', '皇家', '室内老年猫粮 7+', '皇家 室内老年猫粮 7+', array['Royal Canin Indoor 7+'], 'FR'),
  ('dry_food', '皇家', '老年猫粮 12+', '皇家 老年猫粮 12+', array['Royal Canin Ageing 12+'], 'FR'),
  ('dry_food', '皇家', '消化舒适成猫粮', '皇家 消化舒适成猫粮', array['Royal Canin Digestive Care'], 'FR'),
  ('dry_food', '皇家', '泌尿道呵护成猫粮', '皇家 泌尿道呵护成猫粮', array['Royal Canin Urinary Care'], 'FR'),
  ('dry_food', '皇家', '毛球成猫粮', '皇家 毛球成猫粮', array['Royal Canin Hairball Care'], 'FR'),
  ('dry_food', '皇家', '适口性挑嘴成猫粮', '皇家 适口性挑嘴成猫粮', array['Royal Canin Appetite Control'], 'FR'),
  ('dry_food', '皇家', '肾脏处方猫粮', '皇家 肾脏处方猫粮', array['Royal Canin Renal'], 'FR'),
  ('dry_food', '皇家', '波斯成猫粮', '皇家 波斯成猫粮', array['Royal Canin Persian Adult'], 'FR'),
  ('dry_food', '皇家', '英短成猫粮', '皇家 英短成猫粮', array['Royal Canin British Shorthair Adult'], 'FR'),
  ('dry_food', '冠能', '室内成猫粮', '冠能 室内成猫粮', array['Purina Pro Plan Indoor'], 'US'),
  ('dry_food', '冠能', '绝育成猫粮', '冠能 绝育成猫粮', array['Purina Pro Plan Sterilised'], 'US'),
  ('dry_food', '冠能', '消化舒适成猫粮', '冠能 消化舒适成猫粮', array['Purina Pro Plan Sensitive Digestion'], 'US'),
  ('dry_food', '希尔思', 'Adult 7+ 鸡肉老年猫粮', '希尔思 Adult 7+ 鸡肉老年猫粮', array['Hill''s Science Diet Adult 7+'], 'US'),
  ('dry_food', '希尔思', 'Adult 11+ 鸡肉老年猫粮', '希尔思 Adult 11+ 鸡肉老年猫粮', array['Hill''s Science Diet Adult 11+'], 'US'),
  ('dry_food', '希尔思', 'Adult 7+ Indoor 室内老年猫粮', '希尔思 Adult 7+ Indoor 室内老年猫粮', array['Hill''s Science Diet Adult 7+ Indoor'], 'US'),
  ('dry_food', '希尔思', 'Hairball Control 成猫化毛猫粮', '希尔思 Hairball Control 成猫化毛猫粮', array['Hill''s Science Diet Hairball Control'], 'US'),
  ('dry_food', '希尔思', 'Oral Care 成猫口腔护理猫粮', '希尔思 Oral Care 成猫口腔护理猫粮', array['Hill''s Science Diet Oral Care'], 'US'),
  ('dry_food', '希尔思', 'k/d 肾脏处方猫粮', '希尔思 k/d 肾脏处方猫粮', array['Hill''s Prescription Diet k/d'], 'US'),
  ('dry_food', '希尔思', 'i/d 肠胃处方猫粮', '希尔思 i/d 肠胃处方猫粮', array['Hill''s Prescription Diet i/d'], 'US'),
  ('wet_food', '海洋之星', '金枪鱼主食罐', '海洋之星 金枪鱼主食罐', '{}', 'UK'),
  ('wet_food', '海洋之星', '鸡肉主食罐', '海洋之星 鸡肉主食罐', '{}', 'UK'),
  ('wet_food', '小李子', '主食罐 鸭肉配方', '小李子 主食罐 鸭肉配方', '{}', 'DE'),
  ('wet_food', '小李子', '主食罐 鹿肉配方', '小李子 主食罐 鹿肉配方', '{}', 'DE'),
  ('wet_food', '小壳', '主食罐 鸡肉配方', '小壳 主食罐 鸡肉配方', '{}', 'CN'),
  ('wet_food', '小壳', '主食罐 鸭肉配方', '小壳 主食罐 鸭肉配方', '{}', 'CN'),
  ('wet_food', '小壳', '零胶主食罐 鸡肉配方', '小壳 零胶主食罐 鸡肉配方', '{}', 'CN'),
  ('wet_food', '小壳', '零胶主食罐 牛肉配方', '小壳 零胶主食罐 牛肉配方', '{}', 'CN'),
  ('wet_food', '帕特', '主食罐 鸡肉配方', '帕特 主食罐 鸡肉配方', '{}', 'CN'),
  ('wet_food', '帕特', '主食罐 牛肉配方', '帕特 主食罐 牛肉配方', '{}', 'CN'),
  ('wet_food', '阿飞和巴弟', '主食罐 鸭肉配方', '阿飞和巴弟 主食罐 鸭肉配方', '{}', 'CN'),
  ('wet_food', '阿飞和巴弟', '主食罐 鹿肉配方', '阿飞和巴弟 主食罐 鹿肉配方', '{}', 'CN'),
  ('wet_food', '尾巴生活', '主食罐 牛肉配方', '尾巴生活 主食罐 牛肉配方', '{}', 'CN'),
  ('wet_food', '皇家', '老年猫湿粮包 12+', '皇家 老年猫湿粮包 12+', array['Royal Canin Ageing 12+ Wet'], 'FR'),
  ('wet_food', '皇家', '幼猫慕斯罐', '皇家 幼猫慕斯罐', array['Royal Canin Mother & Babycat'], 'FR'),
  ('wet_food', '皇家', '肾脏处方湿粮', '皇家 肾脏处方湿粮', array['Royal Canin Renal Wet'], 'FR'),
  ('wet_food', '皇家', '泌尿道处方湿粮', '皇家 泌尿道处方湿粮', array['Royal Canin Urinary Wet'], 'FR'),
  ('wet_food', '冠能', '幼猫主食湿粮', '冠能 幼猫主食湿粮', array['Purina Pro Plan Kitten Wet'], 'US'),
  ('wet_food', '希尔思', 'Adult 7+ 鸡肉老年猫罐', '希尔思 Adult 7+ 鸡肉老年猫罐', array['Hill''s Science Diet Adult 7+ Wet'], 'US'),
  ('wet_food', '希尔思', 'Adult 11+ 金枪鱼胡萝卜老年猫罐', '希尔思 Adult 11+ 金枪鱼胡萝卜老年猫罐', array['Hill''s Science Diet Adult 11+ Wet'], 'US'),
  ('wet_food', '希尔思', 'k/d 肾脏处方猫罐', '希尔思 k/d 肾脏处方猫罐', array['Hill''s Prescription Diet k/d Wet'], 'US'),
  ('wet_food', '希尔思', 'c/d 泌尿道处方猫罐', '希尔思 c/d 泌尿道处方猫罐', array['Hill''s Prescription Diet c/d Wet'], 'US'),
  ('wet_food', '希尔思', 'i/d 肠胃处方猫罐', '希尔思 i/d 肠胃处方猫罐', array['Hill''s Prescription Diet i/d Wet'], 'US'),
  ('treat', '海洋之星', '金枪鱼零食罐', '海洋之星 金枪鱼零食罐', '{}', 'UK'),
  ('treat', '海洋之星', '三文鱼零食罐', '海洋之星 三文鱼零食罐', '{}', 'UK'),
  ('treat', '小壳', '鱼油棒', '小壳 鱼油棒', '{}', 'CN'),
  ('treat', '小壳', '干猫草棒', '小壳 干猫草棒', '{}', 'CN'),
  ('treat', '小壳', '化毛膏', '小壳 化毛膏', '{}', 'CN'),
  ('treat', '小壳', '金枪鱼零食罐', '小壳 金枪鱼零食罐', '{}', 'CN'),
  ('treat', '小壳', '鸡肉零食罐', '小壳 鸡肉零食罐', '{}', 'CN'),
  ('treat', '小壳', '鸡肉冻干桶', '小壳 鸡肉冻干桶', '{}', 'CN'),
  ('treat', '爱立方', '鸡肉冻干', '爱立方 鸡肉冻干', '{}', 'CN'),
  ('treat', '爱立方', '蛋黄冻干', '爱立方 蛋黄冻干', '{}', 'CN'),
  ('treat', '爱立方', '鸭肉冻干', '爱立方 鸭肉冻干', '{}', 'CN'),
  ('treat', '爱立方', '鹌鹑冻干', '爱立方 鹌鹑冻干', '{}', 'CN'),
  ('treat', '麦富迪', '弗列加特冻干零食', '麦富迪 弗列加特冻干零食', '{}', 'CN'),
  ('medicine', '卫仕', '猫用鱼油', '卫仕 猫用鱼油', '{}', 'CN'),
  ('medicine', '红狗', '猫用营养膏', '红狗 猫用营养膏', '{}', 'CN'),
  ('medicine', '麦德氏', '猫用化毛膏', '麦德氏 猫用化毛膏', '{}', 'CN'),
  ('medicine', '谷登', '猫用六种菌益生菌', '谷登 猫用六种菌益生菌', '{}', 'CN'),
  ('medicine', 'MAG', '猫用益生菌', 'MAG 猫用益生菌', '{}', 'CN'),
  ('medicine', '小壳', '猫用鱼油', '小壳 猫用鱼油', '{}', 'CN'),
  ('medicine', '小壳', '猫用益生菌', '小壳 猫用益生菌', '{}', 'CN'),
  ('medicine', '小壳', '化毛膏', '小壳 化毛膏', '{}', 'CN'),
  ('medicine', 'Purina Pro Plan', 'FortiFlora 猫用益生菌', 'Purina Pro Plan FortiFlora 猫用益生菌', array['冠能 FortiFlora 猫用益生菌'], 'US'),
  ('medicine', 'Proviable-DC', '猫犬益生菌', 'Proviable-DC 猫犬益生菌', '{}', 'US'),
  ('medicine', 'VetriScience', 'Probiotic Everyday 猫用益生菌', 'VetriScience Probiotic Everyday 猫用益生菌', '{}', 'US')
on conflict (item_type, display_name) do update
set
  aliases = excluded.aliases,
  brand = excluded.brand,
  country_region = excluded.country_region,
  product_name = excluded.product_name,
  updated_at = now();
